#!/usr/bin/env bash
#Install and configure HAproxy on your lb-01 server.

apt-get install -y software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-1.8
apt-get -y update
apt-get install -y haproxy=1.8.\*

echo "ENABLED=1" > /etc/default/haproxy

echo "
   listen load_balancer
   bind *:80
   mode http
   balance roundrobin
   option httpclose
   option forwardfor
   server 488586-web-01 54.224.43.201:80 check
   server 488586-web-02 34.207.83.53:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
